### ISSUE TITLE
Specifying and accessing a specific number of non-option arguments

### ISSUE THREAD

**Issue by XSven** [jopt-simple/jopt-simple#103]
Hi  Paul,

I have a challenge to specify a command-line that has some options and exactly
a single non-option argument. This is the specification of the non-option
argument.

OptionSpec<String> key = parser.nonOptions("nbr key").ofType(String.class).describedAs("key");

After parsing a command-line with more than one non-option argument, an

MultipleArgumentsForOptionException

with the message

"Found multiple arguments for option [arguments], but you asked for only one"

was thrown when I have called

options.valueOf(key)

If I would have called

options.valuesOf(key).get(0)

the erroneous use of the command with more than a single non-option agument
remains undiscovered.

A similar inconsistency occures, if the non-option argument is missing.

options.valueOf(key)

returns null

options.valuesOf(key).get(0)

throws an IndexOutOfboundsException.

My question is the following: How can I specify a fixed number of non-option
arguments in a way that access after parsing of an invalid command-line always
throws an OptionException with a meaningful message?

In the past you did work on issue #17 and you did introduce the methods
at(Lea|Mo)st to NonOptionArgumentSpec with the [commit](https://github.com/pholser/jopt-simple/commit/bbe1cd286d0a526657210274128857d6e046efbc#diff-d23819027e700eeacbc269294689a902R70)

Please explain the reason why these methods were never released?

Kind regards
Sven

**Comment by pholser** [comment]
@XSven To be honest, I can't remember the reason for not ultimately including this functionality. I'm willing to look into re-introducing it.

**Comment by XSven** [comment]
Yes please do so. Please consider the following:
From my perspective optional non-option arguments should be transformed to option arguments that means options should be invented for optional non-option arguments. Therefore I would expect only a fixed number and not a range of non-option arguments. The only exception I could think about is if the last non-option argument is a variable list like e.g. a list of files.

**Comment by pholser** [comment]
@XSven What about asking for the non-option args like this, and validating the count yourself?

    OptionSpec<String> nonOptions =
        parser.nonOptions("nbr key").describedAs("key");

    OptionSet options = parser.parse(args);

    List<String> values = options.values(nonOptions);
    if (values.size() != 1) {
        // fail
    }

This seems like a straightforward path to what you want to accomplish, that doesn't over-complicate JOpt Simple's API.

I'm not sure that adding enforced multiplicity of non-option arguments adds enough value to warrant the additional API surface area.

**Comment by XSven** [comment]
Hi Paul,

my design approach for command-line arguments of a program is the following: I am inventing options with or without option arguments for all the "option"al arguments that I want to pass to my program. I am considering all remaining command-line arguments as mandatory non-option arguments. I thought I could specify these mandatory arguments using the nonOptions() method once per mandatory
argument. My expectation was that the parse() method fails with an OptionException, if one of my mandatory non-option argument is missing.

Now I have browsed the JOpt Simple examples again and it seems that I have misunderstood
something. One example shows the

OptionSpec<File> files = parser.nonOptions().ofType( File.class );

specification. I thought this is a specification of one single mandatory non-option file argument but it's not. I don't want to code around JOpt Simple to meet my expectations. Therfore I was glad to see the [Commit](https://github.com/pholser/jopt-simple/commit/bbe1cd286d0a526657210274128857d6e046efbc#diff-d23819027e700eeacbc269294689a902R70) you have made to address the issue #17. In the end I am astonished that enforced multiplicity is missing. For me mandatory arguments have the same signifiance as optional arguments (==options).

Kind regards
Sven

**Comment by pholser** [comment]
@XSven Please have a look at the pull request above and let me know whether this meets your needs. This would go into a 5.1 release. Thanks!

**Comment by pholser** [comment]
I'm closing this issue -- haven't gotten any feedback regarding the PR, and upon further reflection, I'm not convinced that adding this functionality is a must to have in jopt-simple. If necessary, a programmer can check the cardinality of non-option arguments by hand and raise an exception if violated.
