### ISSUE TITLE
Generating bash/zsh completions

### ISSUE THREAD

**Issue by lbergelson** [jopt-simple/jopt-simple#114]
It would be really useful if there was a way to generate bash/zsh tab completion scripts from a configured jopt parser.  Help output is good, but interactive tab completion is even better.  It might be a bit out of scope of the project though.

**Comment by pholser** [comment]
@lbergelson That sounds like a great idea!

@binkley Do you know anything about bash tab completion configuration?

**Comment by lbergelson** [comment]
@pholser We've implemented a initial version of bash completion generation in our command line parsing / documentation generation library which runs on top of jopt-simple.  ( https://github.com/broadinstitute/barclay ).  We add a whole bunch of extra stuff on top of jopt, probably doesn't fall into the "simple" category anymore, but the bash template we use for completions could probably be filled out directly from jopt with some modification.
