### ISSUE TITLE
multiple arguments for a single option

### ISSUE THREAD

**Issue by lbergelson** [jopt-simple/jopt-simple#121]
It would be useful if we could specify multiple arguments for one specification of an option.

i.e. allowing `-f file1 file2 file3` in addition to allowing `-f file1 -f file2 -f file3`

This would allow shell expansion to work correctly: `-f file*`

Allowing this would cause ambiguous parsing with non-option arguments, but I think giving priority to multiple arguments would match existing behavior of most tools, you could separate non-option arguments with `--` if necessary.

**Comment by rsbreidenbach** [comment]
@lbergelson I think this would unnecessarily complicate parsing for a use case - multiple arguments for a single option - that already has viable alternative implementations:

1. Pass the option multiple times: `-f file1 -f file2 -f file3`
2. Pass in a delimited list of arguments and parse them with the application: `-f file1,file2,file3`. The delimiter can defined by the application.
