### ISSUE TITLE
Ability to fetch all OptionSpecs from an OptionSet, including non-options

### ISSUE THREAD

**Issue by knuta** [jopt-simple/jopt-simple#125]
I have a use-case where the location of my non-option parameters relative to other parameters matters. I basically made a find-style boolean logic parser, which accepts input like this:

```
\( foo --or bar \) --and baz
```

When I initially developed this, using jopt-simple 4.6, I used `OptionSet.specs()` to get the list of all specs, and used that to determine the position of the non-option arguments. However, since then #74 has stripped away all the non-option opt handlers, and this information is lost.

I tried inspecting `detectedSpecs` within `OptionSet`, and it appears to have an extra NonOptionArgumentSpec in the beginning of the list (possibly containing $0?). It looks like the original code, before the change in #74, only removed this first entry, but didn't copy the list before doing so, resulting in an issue where multiple calls removed one entry each.

The javadoc of `OptionSet.opts()` gives no indication that the list of OptionSpecs should exclude non-options. Could it be that the original intent was to only remove the first entry, and the real bug was that it wasn't copying the list before doing so?

Jopt-simple 4.9 has been out for two years, so I'd understand if you didn't want to change the behavior of `OptionSet.opts()` again. Would it be possible to add something like  `OptionSet.specsIncludingNonOptions()` which also includes the non-option specs, though?

**Comment by pholser** [comment]
This should be available in 6.0-alpha-3.
