### ISSUE TITLE
API changes report for JOpt Simple

### ISSUE THREAD

**Issue by lvc** [jopt-simple/jopt-simple#129]
Hi,

I'd like to share report on API changes and backward compatibility for the JOpt Simple library: https://abi-laboratory.pro/java/tracker/timeline/jopt-simple/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/net/sf/jopt-simple/jopt-simple/. The tool checks for API changes according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jopt-simple-1](https://user-images.githubusercontent.com/1517837/32209754-fbbcf8e6-be1a-11e7-9926-eb20635578da.png)

![jopt-simple-2](https://user-images.githubusercontent.com/1517837/32209753-fba0f088-be1a-11e7-9c0c-0e0ac7fe6820.png)

**Comment by pholser** [comment]
@lvc Thanks for this! Very useful.
