### ISSUE TITLE
Java 9 support with module-info class

### ISSUE THREAD

**Issue by jiakuan** [jopt-simple/jopt-simple#130]
At the moment, if we use jlink with jopt-simple, the following error occurs:

`Error: module-info.class not found for jopt.simple module`

**Comment by pholser** [comment]
@jiakuan Thanks for this! Please see comment by @twoqubed on your PR. Once his questions are cleared up, we'll roll this in.

**Comment by jiakuan** [comment]
@pholser Thanks for looking at this ticket, I've updated the pull request and added comments too.

**Comment by pholser** [comment]
This should be in 6.0-alpha-3.
