### ISSUE TITLE
Consider abandoning http://pholser.github.io/jopt-simple/

### ISSUE THREAD

**Issue by oliviercailloux** [jopt-simple/jopt-simple#135]
I had still some links pointing to http://pholser.github.io/jopt-simple/. It says there: “Last Published: 2015-06-27  | Version: 4.9”. Of course, at some point, I realized it’s not that this great library has been abandoned during the last three years; it’s just that the website has changed.
Still, I was afraid, for some time.
Please consider redirecting, or even deleting the old website (better force the user to update their bookmark than give outdated information, I’d say), or telling the user (on the front page of the old site) that there’s another website with updated information.

**Comment by marak8** [comment]
Well the new site https://jopt-simple.github.io/jopt-simple returns 404. So it'd be good to keep the old one. ;-)

**Comment by oliviercailloux** [comment]
Well, at time of posting, I had found a new website, more up to date. (I should have written the URL.) Not sure what it was, but I’m sure it existed.

**Comment by rsbreidenbach** [comment]
https://jopt-simple.github.io/jopt-simple is working now.

**Comment by jlmuir** [comment]
The first result for a Google search for _joptsimple_ is <https://pholser.github.io/jopt-simple/> which has the old information:

```
Last Published: 2015-06-27  | Version: 4.9
```

It would be good to get rid of that site (or redirect).

**Comment by oliviercailloux** [comment]
404 again at https://jopt-simple.github.io/jopt-simple. What’s happening?

**Comment by jopt-simple** [comment]
@oliviercailloux Sorry for the trouble -- it seems that, in the process of transferring ownership of the repo to GH user `jopt-simple`, not just anyone of the collaborators is able to publish the `gh-pages` branch. We think we've got things restored now, and so 
https://jopt-simple.github.io/jopt-simple is the authoritative location of the docs.
