### ISSUE TITLE
Examples on github.io are broken

### ISSUE THREAD

**Issue by DaveJarvis** [jopt-simple/jopt-simple#141]
**Replicate**
This likely relates to issue #135.

1. Visit http://jopt-simple.github.io/jopt-simple/examples.html

**Expected**
Examples are visible.

**Actual**
![missing-examples](https://user-images.githubusercontent.com/2131950/49045250-4677c980-f185-11e8-9393-15d184de59c6.png)

**Comment by pholser** [comment]
Whoops. Corrected. Sorry for the trouble...thanks for letting us know!
