### ISSUE TITLE
"Content unavailable" on Google group

### ISSUE THREAD

**Issue by szpak** [jopt-simple/jopt-simple#146]
Trying to reach the discussion group linked in the readme (https://groups.google.com/d/forum/jopt-simple), I've got:
> Content unavailable

Is it still on?

**Comment by pholser** [comment]
@szpak As far as I'm aware, it should be available. Are you a member of the group?

**Comment by szpak** [comment]
No, I'm not. That could be a problem. However, usually the content of the group is freely available to search and browse for anybody (e.g. to check, if a given problem hasn't been reported previously) and only posting requires joining the group.

Do you think it would be sensible also for that group?

**Comment by pholser** [comment]
@szpak I've changed the group settings so that you should be able to see group content without being a member of the group. Give it a try, and let me know how it goes. Thanks!

**Comment by szpak** [comment]
It works as expected, thanks!
