### ISSUE TITLE
Passing argument with comas

### ISSUE THREAD

**Issue by szpak** [jopt-simple/jopt-simple#147]
In [PIT](https://github.com/hcoles/pitest) which uses jopt-simple I would like to pass the following parameters to be used **internally** to create a separate JVM process with:
> -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005

(not to pass it to the main process)

Is it possible to pass it somehow to jopt (with some encoding, etc.)?

Currently it treats it as 4 parameters:
![image](https://user-images.githubusercontent.com/148013/97810628-987cd000-1c75-11eb-9352-8861de5ddee4.png)

Update. There is jopt-simple 4.9 used, but I don't see any related changes in the newer versions.

**Comment by pholser** [comment]
@szpak It appears that pitest configures its option parser like so:

```java
this.jvmArgs = parserAccepts(CHILD_JVM).withRequiredArg()
        .withValuesSeparatedBy(',')
        .describedAs("comma separated list of child JVM args");
```

It's expecting to be handed potentially many values for its JVM args, separated by commas. Right now there isn't a good way in JOpt Simple to say "accept many values for this option with S as a separator, and use T to suppress a separator."

Looping in @hcoles -- might this be better addressed in pitest?
