### ISSUE TITLE
Add support for JDK Jigsaw Modules

### ISSUE THREAD

**Issue by jonatino** [jopt-simple/jopt-simple#149]
It’s not possible to use this library with modular jdk 9+ projects. Please add a module-info.Java with proper exports. Thanks!

**Comment by Jonatino** [comment]
https://www.baeldung.com/java-9-modularity

**Comment by pholser** [comment]
@Jonatino Thanks for this. Would you be willing to submit a pull request with a suitable `module-info.java`? Let me know.

**Comment by Jonatino** [comment]
@pholser would you want to expose the internal package? https://github.com/jopt-simple/jopt-simple/tree/master/src/main/java/joptsimple/internal

Usually things under an internal package are not exposed, but this might cause backwards compatibility with people using your project.

**Comment by pholser** [comment]
@Jonatino I'd say definitely exclude `joptsimple.internal`.

I'd vote for targeting Java 11. I think I will let 5.x stick to a previous JDK, but master/6.x can target Java 11.

**Comment by pholser** [comment]
TBH, I'm going to need to do a lot of catching up on what a proper module of jopt-simple would entail. I've been away from it for too long - and the only modular thing we ever did was to add an `Automatic-Module-Name` manifest entry....

**Comment by A248** [comment]
The general idea is to `export` the packages which constitute the public API (joptsimple and joptsimple.util), `require` the modules which are dependencies (including other JDK modules), and declare service loader details (none). Those are the basic concepts. @pholser If you would like me to review whatever PR is created, feel free to mention.

> Usually things under an internal package are not exposed, but this might cause backwards compatibility with people using your project.

It would be a backwards-compatible change to encapsulate internal packages. Such packages are not public API and are already prone to change in the absence of a module descriptor. Plus, anyone who really wants to break into internals still can, by running on the classpath.

**Comment by pholser** [comment]
@A248 for your perusal - https://github.com/jopt-simple/jopt-simple/pull/150

**Comment by pholser** [comment]
@Jonatino I've merged some changes onto master; have a look and see whether they meet your needs.

I'm now building using JDK 11, targeting Java 8. The JAR should double as a JPMS module and an OSGi bundle, if I've done this correctly.
