### ISSUE TITLE
JOpt Simple's help formatting in order of  insertion.

### ISSUE THREAD

**Issue by cwjcsu** [jopt-simple/jopt-simple#24]
Currently, OptionParser stores the options in a sorted Map(lexicographical), but I need to store them in  order of how they are inserted.

**Comment by JanecekPetr** [comment]
Very much interested in this, indeed.

**Comment by twoqubed** [comment]
One solution would be to extend `[BuiltinHelpFormatter](https://github.com/jopt-simple/jopt-simple/blob/master/src/main/java/joptsimple/BuiltinHelpFormatter.java)` and override `[format](https://github.com/jopt-simple/jopt-simple/blob/master/src/main/java/joptsimple/BuiltinHelpFormatter.java#L90)`.

**Comment by pholser** [comment]
Sounds like no one's been interested in this for a while. Closing.
