### ISSUE TITLE
requirements-checks should be done lazily

### ISSUE THREAD

**Issue by ogregoire** [jopt-simple/jopt-simple#67]
I have this use case where I want either two options present or absent and I can't reflect that using the API only because of an issue at runtime.

Typically, I'm requesting the user to set up his proxy and I use the following:

```
OptionSpec<InetAddress> proxyHost = optionParser.accepts("proxy-host")
  .requiredIf("proxy-port")
  .withRequiredArg()
  .withValuesConvertedBy(new InetAddressConverter());

OptionSpec<Integer> proxyPort = optionParser.accepts("proxy-port")
  .requiredIf("proxy-host")
  .withRequiredArg()
  .ofType(Integer.class);
```

However this will fail because the second line of the first statement checks that `"proxy-host"` is defined, but it is not defined yet since it comes only after.

So the solution would be to check the "required" rules when `optionParser.parse(String[])` is called, not before.

I feel like this use case is legit and that an eager-fail is not what the customer wants in most cases. Plus, checking lazily would enable the framework to gather all issues at once and allow the user to see them all of his/her issues at once, instead of having to compile/test for each of those.

**Comment by tbender85** [comment]
I'm not sure that it negates the issue as a nice idea, however I think @fror could have used an InetSocketAddress with a custom converter to capture both the InetAddress and port in a single argument.

**Comment by JohnGlassmyer** [comment]
I have just come here to ask about mutually required options. In my case, there are three options that I want to require all-present or all-absent.

I tried leaving the first option temporarily unbuilt and passing its OptionSpecBuilder as the requirement for the other two, but then apparently at parse-time that builder wasn't recognized as being the same as the option : (

I guess the alternative to making that work would be to add a public requiredIf method to OptionParser.

**Comment by JohnGlassmyer** [comment]
Although, come to think of it, in my case, two of the options might be applicable in the presence either of the third option of a fourth option. Perhaps that would requires further changes. If I understand correctly, there's not yet a way to say "either A or B is required if C".

**Comment by JohnGlassmyer** [comment]
So, I realize that this would be a lot of added complexity, but maybe you could flesh out option-option dependencies with new types DependencySpec and DependencyBuilder, mirroring the existing OptionSpec and OptionBuilder.

Then you could objectify each option-option dependency (requirement or exclusion - up to this point you've only modeled requirement but exclusion might be useful) with a DependencySpec, like OptionSpec objectifies options. The user could build one with a fluent interface originating on OptionParser and, after parsing arguments, could query the DependencySpec to see whether or not a given requirement had been satisfied. Perhaps DependencyBuilder would allow the user to specify how to respond to violations of the dependency (by throwing an exception, running a provided callback, or doing nothing).

In any event, pulling option-option dependencies out of OptionBuilder and into their own type of entity might make it easier to address the original issue presented here.

**Comment by pholser** [comment]
Not doing this, after so long. Closing.
