### ISSUE TITLE
Exception classes should be public

### ISSUE THREAD

**Issue by sergio-castro** [jopt-simple/jopt-simple#83]
It would be nice if (some of) the exception classes become public.
I was trying to pretty print for my users the output when a required option is not present (MissingRequiredOptionsException) or when a required argument is not there (OptionMissingRequiredArgumentException). I wanted to simplify the implementation just by caching the previously mentioned exceptions but I cannot do it since those classes are not public. Is it possible to change this?

At the moment I have to inspect the resulting OptionSet to show pretty-printed errors (an option or its argument is not present). This is quite cumbersome.

Thanks.

**Comment by pholser** [comment]
See also the discussion in #87.

**Comment by lbergelson** [comment]
I know that I've also wanted to catch exceptions.  We're using `jopt-simple` as part of our command line parser and putting other functionality on top of it.  There have been times that I've wanted to be able to catch specific exceptions and react to them with something other than printing the message.  

I understand that it may be a burden to expose them and then have to support them.

**Comment by pholser** [comment]
I don't foresee ever implementing this. Closing.
